version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=REDIS-PASSWORD

  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:5000 server:app
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app/backend'
    depends_on:
      - redis

  frontend:
    build: ./frontend
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app/frontend'

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
